<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove=".editorconfig" />
	</ItemGroup>

	<ItemGroup>
	  <EditorConfigFiles Include=".editorconfig" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="RAM\InternalRAM\" />
		<Folder Include="RAM\SRAM\" />
		<Folder Include="RAM\WRAM\" />
	</ItemGroup>

</Project>
