<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="RAM\InternalRAM\" />
		<Folder Include="RAM\SRAM\" />
		<Folder Include="RAM\WRAM\" />
	</ItemGroup>

</Project>
